name: Metrics
on:
  # 每天 00:00 更新
  schedule: [{cron: "0 0 * * *"}]
  # 手动触发更新
  workflow_dispatch:
  # 每次 push 到主分支更新
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: # 注意：steps 应该和上面的 permissions 对齐
      - uses: lowlighter/metrics@latest # 破折号前面保留 2 个空格，对齐 steps 的 s
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Gongzihang6
          template: classic
          
          # 布局与美化
          base: activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_padding: 0, 8%
          config_display: large
          
          # 习惯插件修复（关闭 facts 避开 Unexpected error）
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          # 语言插件
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vue, javascript, typescript, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          
          # 3D 日历
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
